import os
from os import getenv
from dotenv import load_dotenv

load_dotenv()
admins = {}
SESSION_NAME = getenv("SESSION_NAME", "session")
BOT_TOKEN = getenv("BOT_TOKEN")
BOT_NAME = getenv("BOT_NAME")
API_ID = int(getenv("API_ID"))
API_HASH = getenv("API_HASH")
MONGODB_URL = getenv("MONGODB_URL")
OWNER_NAME = getenv("OWNER_NAME")
ALIVE_NAME = getenv("ALIVE_NAME")
BOT_PHOTO = getenv("BOT_PHOTO")
DEV_PHOTO = getenv("DEV_PHOTO")
DEV_NAME = getenv("DEV_NAME")
BOT_USERNAME = getenv("BOT_USERNAME")
UPSTREAM_REPO = getenv("UPSTREAM_REPO")
UPSTREAM_BRANCH = getenv("UPSTREM_BRANCH", "main")
ASSISTANT_NAME = getenv("ASSISTANT_NAME")
GROUP_SUPPORT = getenv("GROUP_SUPPORT", "")
UPDATES_CHANNEL = getenv("UPDATES_CHANNEL", "")
SUDO_USERS = list(map(int, getenv("SUDO_USERS", "5497622752").split()))
COMMAND_PREFIXES = list(getenv("COMMAND_PREFIXES", "").split())
ALIVE_IMG = getenv("ALIVE_IMG", "https://telegra.ph/file/090f171f140929eb95633.jpg")
DURATION_LIMIT = int(getenv("DURATION_LIMIT", "900"))
UPSTREAM_REPO = getenv("https://github.com/alhajjiahmed15/u2")
IMG_1 = getenv("IMG_1", "https://telegra.ph/file/e7a2def764502e4f8c9bb.jpg")
IMG_2 = getenv("IMG_2", "https://telegra.ph/file/28c6d6697b35e96e19a7f.jpg")
IMG_3 = getenv("IMG_3", "https://telegra.ph/file/9d849546bbcfec2b01ec9.jpg")
IMG_4 = getenv("IMG_4", "https://telegra.ph/file/3b6137e50891aa2c72a81.jpg")
IMG_5 = getenv("IMG_5", "https://telegra.ph/file/78827dfb6a49b1a8ff0f3.jpg")
